CREATE TABLE IF NOT EXISTS GroupUsers(
	GroupID CHAR(20) NOT NULL,
	UserID CHAR(20) NOT NULL,
    PRIMARY KEY (GroupID, UserID),	-- Added primary key
	FOREIGN KEY (UserID) REFERENCES Users(UserID)
	ON DELETE CASCADE,
	FOREIGN KEY (GroupID) REFERENCES Groups(GroupID)
	ON DELETE CASCADE
);