CREATE TABLE IF NOT EXISTS Groups(
	GroupID CHAR(20) NOT NULL,
	GroupName CHAR(50) NOT NULL,
  UserID CHAR(20) NOT NULL,
	PRIMARY KEY (GroupID),
  FOREIGN KEY (UserID) REFERENCES Users(UserID)
  ON DELETE CASCADE
);