CREATE TABLE IF NOT EXISTS Subtasks(
	SubID CHAR(30) NOT NULL,
	SubName CHAR(50) NOT NULL,
	SubStatus BOOLEAN NOT NULL DEFAULT FALSE,
  TaskID CHAR(30) NOT NULL,
	FOREIGN KEY (TaskID) REFERENCES UserTasks(TaskID) ON DELETE CASCADE
);