CREATE TABLE IF NOT EXISTS UserLists(
	ListID CHAR(30) NOT NULL,
	ListName CHAR(50) NOT NULL,
	UserID CHAR(20) NOT NULL,
	PRIMARY KEY (ListID),
  FOREIGN KEY (UserID) REFERENCES Users(UserID)	ON DELETE CASCADE
);