package com.tasker.backend.entity;

import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;

@Entity
public class Subtask {
    // ------------------------
    // PRIVATE FIELDS
    // ------------------------

    // An autogenerated id (unique for each Subtask in the db)
    @Id
    @GeneratedValue(strategy = GenerationType.AUTO)
    private long id;

    // Subtask name
    private String name;

    // Subtask status (false: incomplete, true: complete)
    private boolean status;

    // Subtask's corresponding UserTask
    private long taskId;


    // ------------------------
    // PUBLIC METHODS
    // ------------------------

    public Subtask() { }

    public Subtask(long id, String name, boolean status) {
        this.id = id;
        this.name = name;
        this.status = status;
    }

    // Getter and setter methods

    public long getId() {
        return id;
    }

    public void setId(long value) {
        this.id = value;
    }

    public String getName() {
        return name;
    }

    public void setName(String value) {
        this.name = value;
    }

    public boolean getStatus() {
        return status;
    }

    public void setStatus(boolean value) {
        this.status = value;
    }
}
