package com.tasker.backend.entity;

import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import java.util.Date;

@Entity
public class UserTask {
    // ------------------------
    // PRIVATE FIELDS
    // ------------------------

    // An autogenerated id (unique for each UserTask in the db)
    @Id
    @GeneratedValue(strategy = GenerationType.AUTO)
    private long id;

    // UserTask name
    private String name;

    // UserTask status (false: incomplete, true: complete)
    private boolean status;

    // UserTask deadline
    private Date deadline;

    // UserTask priority
    private int priority;

    // UserTask description
    private String description;


    // ------------------------
    // PUBLIC METHODS
    // ------------------------

    public UserTask() { }

    public UserTask(long id, String name, boolean status) {
        this.id = id;
        this.name = name;
        this.status = status;
    }

    public UserTask(long id, String name, boolean status, Date deadline, int priority, String description) {
        this.id = id;
        this.name = name;
        this.status = status;
        this.deadline = deadline;
        this.priority = priority;
        this.description = description;
    }

    // Getter and setter methods

    public long getId() {
        return id;
    }

    public void setId(long value) {
        this.id = value;
    }

    public String getName() {
        return name;
    }

    public void setName(String value) {
        this.name = value;
    }

    public boolean getStatus() {
        return status;
    }

    public void setStatus(boolean value) {
        this.status = value;
    }

    public Date getDeadline() {
        return deadline;
    }

    public void setDeadline(Date value) {
        this.deadline = value;
    }
    public int getPriority() {
        return priority;
    }

    public void setPriority(int value) {
        this.priority = value;
    }

    public String getDescription() {
        return description;
    }

    public void setDescription(String value) {
        this.description = value;
    }
}
