CREATE TABLE IF NOT EXISTS GroupLists(
	ListID CHAR(30) NOT NULL,
	ListName CHAR(50) NOT NULL,
	GroupID CHAR(20) NOT NULL,
	PRIMARY KEY (ListID),
  FOREIGN KEY (GroupID) REFERENCES Groups(GroupID) ON DELETE CASCADE
);