CREATE TABLE IF NOT EXISTS Subtasks(
	SubID INTEGER NOT NULL AUTO_INCREMENT,
	SubName CHAR(50) NOT NULL,
	SubStatus BOOLEAN NOT NULL DEFAULT FALSE,
  TaskID INTEGER NOT NULL,
  PRIMARY KEY (SubID),
	FOREIGN KEY (TaskID) REFERENCES UserTasks(TaskID) ON DELETE CASCADE
);