CREATE TABLE IF NOT EXISTS UserTasks(
	TaskID CHAR(30) NOT NULL,
	TaskName CHAR(50) NOT NULL,
	`Status` BOOLEAN NOT NULL DEFAULT FALSE,
	Deadline DATE,
	Priority INTEGER,
	Description TEXT,
  ListID CHAR(30) NOT NULL,
	PRIMARY KEY(TaskID),
	FOREIGN KEY(ListID) REFERENCES UserLists(ListID) ON DELETE CASCADE
);