CREATE TABLE IF NOT EXISTS UserLists(
	ListID INTEGER NOT NULL AUTO_INCREMENT,
	ListName CHAR(50) NOT NULL,
	UserID INTEGER NOT NULL,
	PRIMARY KEY (ListID),
  FOREIGN KEY (UserID) REFERENCES Users(UserID)	ON DELETE CASCADE
);